# fly.toml app configuration file generated for budgetsco on 2023-05-26T22:47:35+05:30

app = "budgetsco"
primary_region = "fra"
kill_signal = "SIGINT"
kill_timeout = "5s"
[env]
  PORT = "8080"

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  [services.concurrency]
    hard_limit = 500
    soft_limit = 450
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
