allowBuilds:
  '@contrast/fn-inspect': false
  '@firebase/util': true
  '@newrelic/native-metrics': false
  '@parcel/watcher': true
  '@prisma/engines': true
  '@scarf/scarf': true
  argon2: true
  esbuild: true
  prisma: true
  protobufjs: true
