name: "Deploy to staging"

on:
  release:
    types:
      - published
  push:
    branches:
      - main
  workflow_dispatch:

env:
  FIREBASE_API_KEY: ${{ vars.FIREBASE_API_KEY }}
  FIREBASE_AUTH_DOMAIN: ${{ vars.FIREBASE_AUTH_DOMAIN }}
  FIREBASE_PROJECT_ID: ${{ vars.FIREBASE_PROJECT_ID }}
  FIREBASE_STORAGE_BUCKET: ${{ vars.FIREBASE_STORAGE_BUCKET }}
  FIREBASE_MESSAGING_SENDER_ID: ${{ vars.FIREBASE_MESSAGING_SENDER_ID }}
  FIREBASE_APP_ID: ${{ vars.FIREBASE_APP_ID }}
  VAPID_KEY: ${{ vars.VAPID_KEY }}
  STR_PRICING_TABLE_ID: ${{ vars.STR_PRICING_TABLE_ID }}
  STR_PUBLISHABLE_KEY: ${{ vars.STR_PUBLISHABLE_KEY }}

jobs:
  vercel:
    runs-on: ubuntu-latest
    name: "Deploy to staging"

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          registry-url: https://registry.npmjs.org/

      - name: Find and Replace FIREBASE_API_KEY - Using Build Variable
        run: find -name "ui.config.ts" -type f -exec sed -i ''s/#{FIREBASE_API_KEY}#/${{ env.FIREBASE_API_KEY }}/g'' {} \;

      - name: Find and Replace FIREBASE_AUTH_DOMAIN - Using Build Variable
        run: find -name "ui.config.ts" -type f -exec sed -i ''s/#{FIREBASE_AUTH_DOMAIN}#/${{ env.FIREBASE_AUTH_DOMAIN }}/g'' {} \;

      - name: Find and Replace FIREBASE_PROJECT_ID - Using Build Variable
        run: find -name "ui.config.ts" -type f -exec sed -i ''s/#{FIREBASE_PROJECT_ID}#/${{ env.FIREBASE_PROJECT_ID }}/g'' {} \;

      - name: Find and Replace FIREBASE_STORAGE_BUCKET - Using Build Variable
        run: find -name "ui.config.ts" -type f -exec sed -i ''s/#{FIREBASE_STORAGE_BUCKET}#/${{ env.FIREBASE_STORAGE_BUCKET }}/g'' {} \;

      - name: Find and Replace FIREBASE_MESSAGING_SENDER_ID - Using Build Variable
        run: find -name "ui.config.ts" -type f -exec sed -i ''s/#{FIREBASE_MESSAGING_SENDER_ID}#/${{ env.FIREBASE_MESSAGING_SENDER_ID }}/g'' {} \;

      - name: Find and Replace FIREBASE_APP_ID - Using Build Variable
        run: find -name "ui.config.ts" -type f -exec sed -i ''s/#{FIREBASE_APP_ID}#/${{ env.FIREBASE_APP_ID }}/g'' {} \;

      - name: Find and Replace VAPID_KEY - Using Build Variable
        run: find -name "ui.config.ts" -type f -exec sed -i ''s/#{VAPID_KEY}#/${{ env.VAPID_KEY }}/g'' {} \;

      - name: Find and Replace STR_PRICING_TABLE_ID - Using Build Variable
        run: find -name "ui.config.ts" -type f -exec sed -i ''s/#{STR_PRICING_TABLE_ID}#/${{ env.STR_PRICING_TABLE_ID }}/g'' {} \;

      - name: Find and Replace STR_PUBLISHABLE_KEY - Using Build Variable
        run: find -name "ui.config.ts" -type f -exec sed -i ''s/#{STR_PUBLISHABLE_KEY}#/${{ env.STR_PUBLISHABLE_KEY }}/g'' {} \;

      - name: "Install packages"
        run: npm install --production=false --legacy-peer-deps

      - name: "Generate prisma schema"
        run: npx prisma generate

      - name: "Remove dev dependencies"
        run: npm prune --production --legacy-peer-deps

      - name: "Build"
        run: NODE_ENV=production DEPLOYMENT_TARGET=vercel npm run build

      - name: "Deploy to Vercel"
        run: |
          prodRun=""
          if [[ ${GITHUB_REF} == "refs/heads/main" ]]; then
            prodRun="--prod"
          fi

          npx vercel --token ${VERCEL_TOKEN} $prodRun
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
